<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div style="padding-top: 1em; padding-bottom: 1em">
                <h2>Classes</h2>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <?php foreach ($this->classes as $class) { ?>
                <a href="/classes/<?php echo urlencode($class->get('name.fqn')) ?>"><?php echo $class->get('name.fqn') ?></a><br/>
            <?php } ?>
        </div>
        <div class="col-sm-9">
            <?php foreach ($this->classes as $class) { ?>
                <?php if ($class->get('name.fqn') == $this->fqn) { ?>
                    <h4><?php echo $class->get('name.fqn') ?></h4>
                    <?php $extendedClass = $class->get('extends') ?>
                    <?php if (is_array($extendedClass) && !empty($extendedClass)) { ?>
                        Extends:
                        <ul>
                            <li><?php echo $extendedClass['name']['fqn'] ?></li>
                        </ul>
                    <?php } ?>
                    <?php $implementedInterfaces = $class->get('implements') ?>
                    <?php if (is_array($implementedInterfaces) && !empty($implementedInterfaces)) { ?>
                        Implements:
                        <ul>
                        <?php foreach ($implementedInterfaces as $implementedInterface) { ?>
                            <li><?php echo $implementedInterface['name']['fqn'] ?></li>
                        <?php } ?>
                        </ul>
                    <?php } ?>
                    <?php $usagesWithNew = $class->get('usages.new') ?>
                    <?php if (is_array($usagesWithNew) && !empty($usagesWithNew)) { ?>
                        Usages with new:
                        <ul>
                        <?php foreach ($usagesWithNew as $usageWithNew) { ?>
                            <li><?php echo $usageWithNew['context'] ?></li>
                        <?php } ?>
                        </ul>
                    <?php } ?>
                    <?php $usagesInTypeDeclaration = $class->get('usages.type-declaration') ?>
                    <?php if (is_array($usagesInTypeDeclaration) && !empty($usagesInTypeDeclaration)) { ?>
                        Usages in type declaration:
                        <ul>
                        <?php foreach ($usagesInTypeDeclaration as $usageInTypeDeclaration) { ?>
                            <li><?php echo $usageInTypeDeclaration['context'] ?></li>
                        <?php } ?>
                        </ul>
                    <?php } ?>
                    <?php $usagesWithConstFetch = $class->get('usages.const-fetch') ?>
                    <?php if (is_array($usagesWithConstFetch) && !empty($usagesWithConstFetch)) { ?>
                        Usages with const fetch:
                        <ul>
                        <?php foreach ($usagesWithConstFetch as $usageWithConstFetch) { ?>
                            <li><?php echo $usageWithConstFetch['context'] ?></li>
                        <?php } ?>
                        </ul>
                    <?php } ?>
                    <?php $usagesWithStaticCall = $class->get('usages.static-call') ?>
                    <?php if (is_array($usagesWithStaticCall) && !empty($usagesWithStaticCall)) { ?>
                        Usages with static call:
                        <ul>
                        <?php foreach ($usagesWithStaticCall as $usageWithStaticCall) { ?>
                            <li><?php echo $usageWithStaticCall['context'] ?></li>
                        <?php } ?>
                        </ul>
                    <?php } ?>
                    <?php $usagesWithUse = $class->get('usages.use') ?>
                    <?php if (is_array($usagesWithUse) && !empty($usagesWithUse)) { ?>
                        Usages with use in files:
                        <ul>
                        <?php foreach ($usagesWithUse as $usageWithUse) { ?>
                            <li><?php echo $usageWithUse['file'] ?></li>
                        <?php } ?>
                        </ul>
                    <?php } ?>
                    <br/>
                    <br/>
                    <br/>
                    <?php ini_set('xdebug.var_display_max_depth', 10); var_dump($class); ?>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
</div>
