<?php
$this->headStyle()->appendStyle(<<<CSS
    .chart rect {
        fill: steelblue;
    }
    
    .chart text {
        fill: white;
        font: 10px sans-serif;
        text-anchor: end;
    }
CSS
);

$this->inlineScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/d3/4.4.1/d3.js');
$this->inlineScript()->appendScript(<<<JS
    jQuery(function() {
        var data = [4, 8, 15, 16, 23, 42];
        var labels = ['foo', 'bar', 'baz', 'goo', 'gar', 'gaz'];

        var width = 420;
        var barHeight = 20;

        var x = d3.scaleLinear()
            .domain([0, d3.max(data)])
            .range([0, width]);

        var chart = d3.select(".chart")
            .attr("width", width)
            .attr("height", barHeight * data.length);

        var bar = chart.selectAll("g")
            .data(data)
          .enter().append("g")
            .attr("transform", function(d, i) { return "translate(0," + i * barHeight + ")"; });

        bar.append("rect")
            .attr("width", x)
            .attr("height", barHeight - 1);

        bar.append("text")
            .attr("x", function(d) { return x(d) - 3; })
            .attr("y", barHeight / 2)
            .attr("dy", ".35em")
            .text(function(d) { return d; });
    });
JS
);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div style="padding-top: 1em; padding-bottom: 1em">
                <h2>Overview</h2>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-sm-12">
            <svg class="chart"></svg>
        </div>
    </div>
</div>