<?php
$this->headStyle()->appendStyle(<<<CSS
    .chart rect {
        fill: steelblue;
    }

    .chart text {
        fill: white;
        font: 10px sans-serif;
        text-anchor: end;
    }
CSS
);

$this->inlineScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/d3/4.4.1/d3.js');
$this->inlineScript()->appendScript(<<<JS
    jQuery(function() {
        var data = [4, 8, 15, 16, 23, 42];
        var color = d3.scaleOrdinal(d3.schemeCategory20c);

        var width = 420;
        var height = 300;

        var outerRadius = d3.min([width, height]) / 2;
        var innerRadius = outerRadius / 2;
        var arc = d3.arc()
            .innerRadius(innerRadius)
            .outerRadius(outerRadius);

        var svg = d3.select("div.chart")
            .append("svg")
              .attr("width", width)
              .attr("height", height);

        var pie = d3.pie();

        var arcs = svg.selectAll("g.arc")
              .data(pie(data))
            .enter().append("g")
              .attr("class", "arc")
              .attr("transform", "translate(" + outerRadius +  ", " + outerRadius + ")");

        arcs.append("path")
              .attr("fill", function(d, i) {
                  return color(i);
              })
              .attr("stroke", "white")
              .attr("d", arc);
    });
JS
);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div style="padding-top: 1em; padding-bottom: 1em">
                <h2>Overview</h2>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-sm-12">
            <div class="chart"></div>
        </div>
    </div>
</div>