<?php

$this->inlineScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/d3/4.4.1/d3.js');
$this->inlineScript()->appendScript(<<<JS
    jQuery(function() {
        var color = d3.scaleOrdinal(d3.schemeCategory20c);

        var width = 500;
        var height = 300;

        var legendRectSize = 18;
        var legendSpacing = 4;

        var outerRadius = d3.min([width, height]) / 2;
        var innerRadius = outerRadius / 2;
        var arc = d3.arc()
            .innerRadius(innerRadius)
            .outerRadius(outerRadius);

        var svg = d3.select("div.chart")
            .append("svg")
              .attr("width", width)
              .attr("height", height)
            .append("g")
              .attr("transform", "translate(" + outerRadius +  ", " + outerRadius + ")");

        var pie = d3.pie()
            .sort(null);

        d3.json("/d3-get-data", function(error, data) {
            if (error) throw error;

            var arcs = svg.selectAll("g.arc")
                  .data(pie(data))
                .enter().append("g")
                  .attr("class", "arc");
                  // .attr("transform", "translate(" + outerRadius +  ", " + outerRadius + ")");

            arcs.append("path")
                  .attr("fill", function(d, i) {
                      return color(i);
                  })
                  .attr("stroke", "white")
                  .attr("d", arc);

            var legends = svg.selectAll("g.legend")
                  .data(color.domain())
                .enter().append("g")
                  .attr("class", "legend")
                  .attr("transform", function (d, index) {
                       var height = legendRectSize + legendSpacing;
                       var offset = height * color.domain().length / 2;
                       var horizontal = outerRadius + 2 * legendRectSize;
                       var vertical = index * height - offset;

                       return "translate(" + horizontal + "," + vertical + ")";
                  });

            legends.append("rect")
                .attr("width", legendRectSize)
                .attr("height", legendRectSize)
                .style("fill", color)
                .style("stroke", color);
        });
    });
JS
);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div style="padding-top: 1em; padding-bottom: 1em">
                <h2>Overview</h2>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-sm-12">
            <div class="chart"></div>
        </div>
    </div>
</div>