<?php
$this->headStyle()->appendStyle(<<<CSS
    .chart text {
        fill: black;
        font: 10px sans-serif;
        text-anchor: begin;
    }

    .chart {
        border: 1px solid black;
    }
     
CSS
);

$this->inlineScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/d3/4.4.1/d3.js');
$this->inlineScript()->appendScript(<<<JS
    jQuery(function() {

        var svg = d3.select("svg");
        svg.attr('width', '420').attr('height', '240');

        var margin = {"top": 20, "right": 80, "bottom": 20, "left": 40};
        var width = svg.attr("width") - margin.left - margin.right;
        var height = svg.attr("height") - margin.top - margin.bottom;
        console.log('Width:' + width + ', Height:' + height);

        var g = svg.append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");

        var x = d3.scaleTime().range([0, width]);
        var y = d3.scaleLinear().range([0, height]);
        var z = d3.scaleOrdinal(d3.schemeCategory10);

        var line = d3.line()
            .curve(d3.curveBasis)
            .x(function (d) { return x(d.date); })
            .y(function (d) { return y(d.temperature); });

        d3.json("d3-line-chart-data", function (cities) {

            cities.forEach(function (city) {
                city.values.forEach(function (value) {
                    value.date = Date.parse(value.date);
                });
            });

            console.log(cities);

            x.domain([
                d3.min(cities, function (c) { return d3.min(c.values, function (d) { return d.date; }) }),
                d3.max(cities, function (c) { return d3.max(c.values, function (d) { return d.date; }) })
            ]);
            y.domain([
                d3.min(cities, function (c) { return d3.min(c.values, function (d) { return d.temperature; }) }),
                d3.max(cities, function (c) { return d3.max(c.values, function (d) { return d.temperature; }) })
            ]);
            z.domain(cities.map(function (c) { return c.id; }));

            console.log(x);
            console.log(y);

            var city = g.selectAll(".city")
                .data(cities)
                .enter().append("g")
                  .attr("class", "city");

            city.append("path")
                .attr("class", "line")
                .attr("d", function(d) { return line(d.values); })
                .style("stroke", function(d) { return z(d.id); })
                .style("fill", "none");
            
            city.append("text")
                .datum(function (d) { return { id: d.id, value: d.values[d.values.length - 1]}; })
                .attr("transform", function (d) { return "translate(" + x(d.value.date) + "," + y(d.value.temperature) + ")"; })
                .attr("dx", 3)
                .attr("dy", "0.35em")
                .style("font", "10px sans-serif")
                .text(function (d) { return d.id; })
                .co;
        });

    });

JS
);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div style="padding-top: 1em; padding-bottom: 1em">
                <h2>Overview</h2>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-sm-12">
            <svg class="chart"></svg>
        </div>
    </div>
</div>