<?php

$this->inlineScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/d3/4.4.1/d3.js');
$this->inlineScript()->appendScript(<<<JS
    jQuery(function() {
        var data = {
            "name":"foo",
            "children": [
                {
                    "name": "bar",
                    "children": [
                        {
                            "name":"baz",
                            "value":12
                        },
                        {
                            "name":"bat",
                            "value":18
                        }
                    ]
                },
                {
                    "name": 11,
                    "value": 5
                }
            ]
        };
        var color = d3.scaleOrdinal(d3.schemeCategory20c);

        var width = 420;
        var height = 300;

        var outerRadius = d3.min([width, height]) / 2;
        var innerRadius = outerRadius / 2;

        var svg = d3.select("div.chart")
            .append("svg")
              .attr("width", width)
              .attr("height", height)
            .append("g")
              .attr("transform", "translate(" + outerRadius +  ", " + outerRadius + ")");

        var hierarchy = d3.hierarchy(data);
        console.log(hierarchy);

        var partition = d3.partition()
            .size([2 * Math.PI, outerRadius * outerRadius]);

        var arc = d3.arc()
            .startAngle(function(d) { return d.x; })
            .endAngle(function(d) { return d.x + d.dx; })
            .innerRadius(function(d) { return Math.sqrt(d.y); })
            .outerRadius(function(d) { return Math.sqrt(d.y + d.dy); });

        var path = svg.selectAll("path")
              .data(hierarchy)
            .enter().append("path")
              .attr("fill", function(d, i) {
                  return color(i);
              })
              .attr("stroke", "white")
              .attr("d", arc);

        console.log(hierarchy);
    });
JS
);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div style="padding-top: 1em; padding-bottom: 1em">
                <h2>Overview</h2>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-sm-12">
            <div class="chart"></div>
        </div>
    </div>
</div>