<?php
$labels = '';
foreach ($this->names as $name) {
    $labels .= '"'.addslashes($name).'",';
}
$labels = rtrim($labels, ', ');
$data = implode(',', $this->amounts);

$this->inlineScript()->appendScript(<<<JS
    jQuery(function() {
        var data = {
            labels: [{$labels}],
            datasets: [
                {
                    data: [{$data}]
                }
            ]
        };

        var ctx = document.getElementById("myChart");

        var myChart = new Chart(ctx,{
            type: "doughnut",
            data: data
        });
    });
JS
);
?>
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-sm-6">
            <canvas id="myChart" width="200" height="200"></canvas>
        </div>
    </div>
</div>