<html>
<body>
    <?php foreach ($this->classes as $class) { ?>
        <p>
            <h4><?php echo $class->get('fqn') ?></h4>
            <?php $usagesWithNew = $class->get('usages.new') ?>
            <?php if (is_array($usagesWithNew) && !empty($usagesWithNew)) { ?>
                Usages with new:
                <ul>
                <?php foreach ($usagesWithNew as $usageWithNew) { ?>
                    <li><?php echo $usageWithNew['context'] ?></li>
                <?php } ?>
                </ul>
            <?php } ?>
            <?php $usagesWithUse = $class->get('usages.use') ?>
            <?php if (is_array($usagesWithUse) && !empty($usagesWithUse)) { ?>
                Usages with use:
                <ul>
                <?php foreach ($usagesWithUse as $usageWithUse) { ?>
                    <li><?php echo $usageWithUse['file'] ?></li>
                <?php } ?>
                </ul>
            <?php } ?>
            <?php $usagesInTypeDeclaration = $class->get('usages.type-declaration') ?>
            <?php if (is_array($usagesInTypeDeclaration) && !empty($usagesInTypeDeclaration)) { ?>
                Usages in type declaration:
                <ul>
                <?php foreach ($usagesInTypeDeclaration as $usageInTypeDeclaration) { ?>
                    <li><?php echo $usageInTypeDeclaration['context'] ?></li>
                <?php } ?>
                </ul>
            <?php } ?>
        </p>
    <?php } ?>
</body>
</html>

