<?php
$labels = '';
foreach ($this->names as $name) {
    $labels .= '"'.addslashes($name).'",';
}
$labels = rtrim($labels, ', ');
$data = implode(',', $this->amounts);

$this->inlineScript()->appendScript(<<<JS
    jQuery(function() {
        var data = {
            labels: [{$labels}],
            datasets: [
                {
                    data: [{$data}],
                    backgroundColor: [
                        '#803690',
                        '#369080',
                        '#908036',
                        '#00ADF9',
                        '#ADF900',
                        '#F900AD',
                        '#46BFBD',
                        '#BFBD46',
                        '#BD46BF',
                        '#FDB45C',
                        '#B45CFD',
                        '#5CFDB4',
                        '#949FB1',
                        '#9FB194',
                        '#4D5360',
                        '#53604D',
                        '#604D53'
                    ]
                }
            ]
        };

        var ctx = document.getElementById("myChart");

        var myChart = new Chart(ctx,{
            type: "doughnut",
            data: data
        });
    });
JS
);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div style="padding-top: 1em; padding-bottom: 1em">
                <h2>Overview</h2>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-sm-6">
            <canvas id="myChart" width="200" height="200"></canvas>
        </div>
    </div>
</div>